# -*- coding: utf-8 -*-
"""Gakusyu.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mH9n78TkblitYjuzhPLMVOlIe3kN2Z0J
"""

import os
import json
import re

def ChkCrfJson(fileName,searchTxt):

  # JsonFileLoad
  opJson = open(fileName,"r")
  jsonLoad = json.load(opJson)

  wkWord = ""
  # CRFJson を行ごとに情報整理
  for lin in in jsonLoad:

    # dict 型の時のみ処理対象
    if isinstance(lin,dict):
      word = lin['word']
      flg = lin['flg']
      
      # 値として検知されている単語を抽出
      if "VAL" in flg:
        wkWord = wkWord + word 

    elif isinstance(lin,str):

      # 連結したフラグありのWordから検索
      m = re.search(searchTxt,wkWord)
      # 検索対象が見つかったら抜ける
      if m is not None:
        result = wkWord
        break
      wkWord = ""
#-------------------------------------------------------------------------